version: '2'
services:
  app:
    build: .
    environment:
      NODE_ENV: test
    command: npm run test
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    volumes:
      - ./data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
